/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Database.Buah;
import Database.Sayuran;
import Database.Tanaman;
import Database.riwayat;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fx506
 */
public class createdata extends javax.swing.JFrame {
    
    String idAdmin;
    
    public createdata(String idAdmin) throws SQLException {
        initComponents();
        this.idAdmin = idAdmin;
    }
    
    private void clearFieldSayur(){
        IDTANAMANSAYUR.setText("");
        NAMATANAMANSAYUR.setText("");
        KONDISITANAMANSAYUR.setText("");
        METODEPENANAMAN.setText("");
        MUSIMTANAM.setText("");
        IDKARYAWANSAYUR.setText("");
        TANGGALTANAMSAYUR.setText("");
        JUMLAHTANAMSAYUR.setText("");
    }
    
    private void clearFieldBuah(){
        IDTANAMANBUAH.setText("");
        NAMATANAMANBUAH.setText("");
        KONDISITANAMANBUAH.setText("");
        BENTUKBUAH.setText("");
        TINGKATKEMATANGAN.setText("");
        IDKARYAWANBUAH.setText("");
        TANGGALTANAMBUAH.setText("");
        JUMLAHTANAMBUAH.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        IDTANAMANSAYUR = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NAMATANAMANSAYUR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        KONDISITANAMANSAYUR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        METODEPENANAMAN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MUSIMTANAM = new javax.swing.JTextField();
        IDTANAMANBUAH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NAMATANAMANBUAH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        KONDISITANAMANBUAH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BENTUKBUAH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TINGKATKEMATANGAN = new javax.swing.JTextField();
        SUBMITSAYUR = new javax.swing.JButton();
        SUBMITBUAH = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        IDKARYAWANSAYUR = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TANGGALTANAMSAYUR = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        JUMLAHTANAMSAYUR = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        IDKARYAWANBUAH = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TANGGALTANAMBUAH = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        JUMLAHTANAMBUAH = new javax.swing.JTextField();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, 40));
        getContentPane().add(IDTANAMANSAYUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 160, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jLabel2.setMaximumSize(new java.awt.Dimension(15, 18));
        jLabel2.setMinimumSize(new java.awt.Dimension(15, 18));
        jLabel2.setPreferredSize(new java.awt.Dimension(15, 18));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 100, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA TANAMAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 100, -1));

        NAMATANAMANSAYUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMATANAMANSAYURActionPerformed(evt);
            }
        });
        getContentPane().add(NAMATANAMANSAYUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 160, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KONDISI TANAMAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 100, -1));
        getContentPane().add(KONDISITANAMANSAYUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 160, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("METODE PENANAMAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 100, -1));
        getContentPane().add(METODEPENANAMAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 160, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MUSIM TANAM");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 100, -1));
        getContentPane().add(MUSIMTANAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 160, -1));
        getContentPane().add(IDTANAMANBUAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 160, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 100, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAMA TANAMAN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 100, 20));
        getContentPane().add(NAMATANAMANBUAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 160, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KONDISI TANAMAN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 100, -1));
        getContentPane().add(KONDISITANAMANBUAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 160, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BENTUK BUAH");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 100, -1));
        getContentPane().add(BENTUKBUAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 160, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TINGKAT KEMATANGAN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 100, -1));
        getContentPane().add(TINGKATKEMATANGAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 160, -1));

        SUBMITSAYUR.setText("SUBMIT");
        SUBMITSAYUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITSAYURActionPerformed(evt);
            }
        });
        getContentPane().add(SUBMITSAYUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 110, 30));

        SUBMITBUAH.setText("SUBMIT");
        SUBMITBUAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITBUAHActionPerformed(evt);
            }
        });
        getContentPane().add(SUBMITBUAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, 110, 30));

        jLabel11.setBackground(new java.awt.Color(0, 102, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BUAH");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 100, -1));

        jLabel12.setBackground(new java.awt.Color(0, 102, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SAYUR");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 100, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID KARYAWAN");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 100, -1));
        getContentPane().add(IDKARYAWANSAYUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 160, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TANGGAL TANAM");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 100, -1));
        getContentPane().add(TANGGALTANAMSAYUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 160, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("JUMLAH TANAM");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 100, -1));
        getContentPane().add(JUMLAHTANAMSAYUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 160, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ID KARYAWAN");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 100, -1));
        getContentPane().add(IDKARYAWANBUAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 160, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TANGGAL TANAM");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 100, -1));
        getContentPane().add(TANGGALTANAMBUAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, 160, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("JUMLAH TANAM");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 100, -1));
        getContentPane().add(JUMLAHTANAMBUAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 160, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Green Modern Plant Store Login Page Desktop Prototype (6).png"))); // NOI18N
        BG.setText("jLabel1");
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        menuadmin createdata = new menuadmin(this.idAdmin);
        createdata.setVisible(true);
        createdata.pack();
        createdata.setLocationRelativeTo(null);
        createdata.setDefaultCloseOperation(menuadmin.EXIT_ON_CLOSE);
        this.dispose();
        setVisible(false);        
    }//GEN-LAST:event_backActionPerformed

    private void SUBMITBUAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITBUAHActionPerformed
        try {
            String idBuah = IDTANAMANBUAH.getText();
            String nama = NAMATANAMANBUAH.getText();
            String kondisi = KONDISITANAMANBUAH.getText();
            String bentuk = BENTUKBUAH.getText();
            String kematangan = TINGKATKEMATANGAN.getText();
            String idkaryawanbuah = IDKARYAWANBUAH.getText();
            String tanggaltanambuah = TANGGALTANAMBUAH.getText();
            String jumlahtanambuah = JUMLAHTANAMBUAH.getText();

            // Memeriksa apakah ada data yang kosong sebelum mengirim
            if (idBuah.isEmpty() || nama.isEmpty() || kondisi.isEmpty() || bentuk.isEmpty() || kematangan.isEmpty() || idkaryawanbuah.isEmpty() || tanggaltanambuah.isEmpty() || jumlahtanambuah.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap lengkapi semua field sebelum mengirim data.");
            } else {
                Tanaman.createTanaman(idBuah, nama, kondisi, this.idAdmin);
                Buah.createbuah(idBuah, nama, kondisi, idkaryawanbuah, bentuk, kematangan);
                riwayat.createriwayat(tanggaltanambuah, jumlahtanambuah, idkaryawanbuah, idBuah);
                JOptionPane.showMessageDialog(null, "BERHASIL MENAMBAHKAN");
                clearFieldBuah();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_SUBMITBUAHActionPerformed

    private void NAMATANAMANSAYURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMATANAMANSAYURActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMATANAMANSAYURActionPerformed

    private void SUBMITSAYURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITSAYURActionPerformed
        try {
            String idSayur = IDTANAMANSAYUR.getText();
            String nama = NAMATANAMANSAYUR.getText();
            String kondisi = KONDISITANAMANSAYUR.getText();
            String metode = METODEPENANAMAN.getText();
            String musim = MUSIMTANAM.getText();
            String idkaryawansayur = IDKARYAWANSAYUR.getText();
            String tanggaltanamsayur = TANGGALTANAMSAYUR.getText();
            String jumlahtanamsayur = JUMLAHTANAMSAYUR.getText();

            // Memeriksa apakah ada data yang kosong sebelum mengirim
            if (idSayur.isEmpty() || nama.isEmpty() || kondisi.isEmpty() || metode.isEmpty() || musim.isEmpty() || idkaryawansayur.isEmpty() || tanggaltanamsayur.isEmpty() || jumlahtanamsayur.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap lengkapi semua field sebelum mengirim data.");
            } else {
                Tanaman.createTanaman(idSayur, nama, kondisi, this.idAdmin);
                Sayuran.createsayur(idSayur, nama, kondisi, idkaryawansayur, metode, musim);
                riwayat.createriwayat(tanggaltanamsayur, jumlahtanamsayur, idkaryawansayur, idSayur);
                JOptionPane.showMessageDialog(null, "BERHASIL MENAMBAHKAN");
                clearFieldSayur();
            }
        } catch (SQLException ex) {
            Logger.getLogger(createdata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SUBMITSAYURActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new createdata("001").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(createdata.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BENTUKBUAH;
    private javax.swing.JLabel BG;
    private javax.swing.JTextField IDKARYAWANBUAH;
    private javax.swing.JTextField IDKARYAWANSAYUR;
    private javax.swing.JTextField IDTANAMANBUAH;
    private javax.swing.JTextField IDTANAMANSAYUR;
    private javax.swing.JTextField JUMLAHTANAMBUAH;
    private javax.swing.JTextField JUMLAHTANAMSAYUR;
    private javax.swing.JTextField KONDISITANAMANBUAH;
    private javax.swing.JTextField KONDISITANAMANSAYUR;
    private javax.swing.JTextField METODEPENANAMAN;
    private javax.swing.JTextField MUSIMTANAM;
    private javax.swing.JTextField NAMATANAMANBUAH;
    private javax.swing.JTextField NAMATANAMANSAYUR;
    private javax.swing.JButton SUBMITBUAH;
    private javax.swing.JButton SUBMITSAYUR;
    private javax.swing.JTextField TANGGALTANAMBUAH;
    private javax.swing.JTextField TANGGALTANAMSAYUR;
    private javax.swing.JTextField TINGKATKEMATANGAN;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
