/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Database.riwayat;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author fx506
 */
public class riwayattanamkaryawan extends javax.swing.JFrame {

    public riwayattanamkaryawan() throws SQLException {
        initComponents();
        setTableRiwayat();

    }
    
    private void setTableRiwayat() throws SQLException{
        DefaultTableModel model = (DefaultTableModel) tabelriwayat.getModel();
        model.setRowCount(0);
        ArrayList<riwayat> dataRiwayat = riwayat.readriwayat();
        for (riwayat Riwayat : dataRiwayat) {
            String tanggal = Riwayat.getTanggaltanam();
            String jumlah = Riwayat.getJumlahtanam();
            String idtanaman = Riwayat.getIdtanaman();
            String idkaryawan = Riwayat.getIdkaryawan();
            String[] row = {tanggal,jumlah,idkaryawan,idtanaman};
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelriwayat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 180, 40));

        tabelriwayat.setBackground(new java.awt.Color(0, 102, 51));
        tabelriwayat.setForeground(new java.awt.Color(255, 255, 255));
        tabelriwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TANGGAL TANAM", "JUMLAH TANAM", "KARYAWAN", "TANAMAN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelriwayat);
        if (tabelriwayat.getColumnModel().getColumnCount() > 0) {
            tabelriwayat.getColumnModel().getColumn(0).setResizable(false);
            tabelriwayat.getColumnModel().getColumn(1).setResizable(false);
            tabelriwayat.getColumnModel().getColumn(2).setResizable(false);
            tabelriwayat.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 1120, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Green Modern Plant Store Login Page Desktop Prototype (13).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showdatakaryawan riwayatpanenkaryawan = new showdatakaryawan();
        riwayatpanenkaryawan.setVisible(true);
        riwayatpanenkaryawan.pack();
        riwayatpanenkaryawan.setLocationRelativeTo(null);
        riwayatpanenkaryawan.setDefaultCloseOperation(showdatakaryawan.EXIT_ON_CLOSE);
        this.dispose();
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(riwayattanamkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(riwayattanamkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(riwayattanamkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(riwayattanamkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new riwayattanamkaryawan().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(riwayattanamkaryawan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelriwayat;
    // End of variables declaration//GEN-END:variables
}
